export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_MESSAGE = 'ADD_TO_CART_MESSAGE';
export const DELETE_CART_ITEM_MESSAGE = 'DELETE_CART_ITEM_MESSAGE';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';